#!/usr/bin/env bash
# PreToolUse hook — block hand-edits to generated / dependency / build-output
# files. Exit 2 blocks the tool call and tells Claude why.
set -euo pipefail

input="$(cat)"
file="$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty')"
[ -z "$file" ] && exit 0

base="$(basename "$file")"

case "$base" in
  composer.lock|package-lock.json|yarn.lock)
    echo "Refusing to hand-edit $base — it is generated by the package manager. Run the install/update command instead (e.g. composer install / npm install)." >&2
    exit 2 ;;
esac

case "$file" in
  */vendor/*)
    echo "Refusing to edit $file — vendor/ is managed by Composer and wiped on install. Patch from plugin code or send an upstream PR." >&2
    exit 2 ;;
  */node_modules/*)
    echo "Refusing to edit $file — node_modules/ is managed by npm." >&2
    exit 2 ;;
  */nxbuild/*)
    echo "Refusing to edit $file — nxbuild/ is build output written by the watcher. Edit the source in nxdev/ instead." >&2
    exit 2 ;;
esac

exit 0
