const IconList = [
  "fab fa-facebook",
  "fab fa-facebook-f",
  "fab fa-twitter",
  "fab fa-twitter-square",
  "fab fa-instagram",
  "fab fa-youtube",
  "fab fa-linkedin",
  "fab fa-linkedin-in",
  "fab fa-flickr",
  "fab fa-github",
  "fab fa-github-square",
  "fab fa-github-alt",
  "fab fa-google-plus",
  "fab fa-pinterest",
  "fab fa-reddit",
  "fab fa-skype",
  "fab fa-stack-overflow",
  "fab fa-whatsapp",
  "fab fa-vimeo-v",
  "fab fa-tumblr",
  "fab fa-dribbble",
  "fab fa-quora",
  "fab fa-foursquare",
  "fab fa-wordpress-simple",
  "fab fa-facebook-square",
  "fab fa-stumbleupon",
  "fab fa-yahoo",
  "fab fa-blogger-b",
  "fab fa-soundcloud",
];

export default IconList;
