name: Generate WordPress Archive
on:
  workflow_dispatch:
  workflow_call:
    # This allows other workflows to call this and get the zip
    outputs:
      artifact-name:
        description: 'The name of the uploaded artifact'
        value: 'notificationx'

jobs:
  generate-archive:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Updated to v4 for better performance

      - name: Generating zip
        uses: rudlinkon/action-wordpress-build-zip@master
        with:
          # npm-run-build: true
          install-composer: false